apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: fluentd-logging
  name: fluentd-cloud-logging
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fluentd-cloud-logging
  labels:
    k8s-app: fluentd-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: fluentd-cloud-logging
  namespace: kube-system
