[template]
src = "application_default_credentials.json.tmpl"
dest = "/etc/google/auth/application_default_credentials.json"
keys = [
    "/google/fluentd/project/id",
    "/google/fluentd/private/key/id",
    "/google/fluentd/private/key",
    "/google/fluentd/client/email",
    "/google/fluentd/client/id",
    "/google/fluentd/client/x509/cert/url",
]
